### ISSUE TITLE
docker container link broken

### ISSUE THREAD

**Issue by norahvii** [ceteri/jem-video#1]
I attempted to click the docker container link in the read me and it did not work.

**Comment by ceteri** [comment]
Thank you @norahvii 

No idea why the account is having troubles (`404` NOT FOUND errors) on the Docker Hub side, although the source for the container is in: https://github.com/ceteri/jem-docker

I haven't talked with O'Reilly Media in a few years, and they've moved their URLs a lot for the related content.  So I won't be able to make changes on their side (if they have any links pointing into this repo)

Although what I can do is put this container onto Docker Hub through our company account, which I know is working.  I will update after customer calls conclude this morning.

**Comment by ceteri** [comment]
@norahvii ,
Docker Hub had remapped their URLs.

The correct one to use is now updated in the `README` of this repo: <https://registry.hub.docker.com/r/ceteri/jem>

**Comment by norahvii** [comment]
@ceteri 
Thanks for fixing that. 

I was able to copy out the notebooks via:  `docker cp 8a7047d4370f710834ce31efb10176701d5f2a71d440a8bba81e942f6278d04f:/home/atlas .\myfolder\`
